/*
 * StockQuotes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;
using Server.Attributes;
using Server.Managers;
using Swashbuckle.AspNetCore.Annotations;

namespace Server.Controllers {
	/// <summary>
	/// </summary>
	[ApiController]
	public class TokenApiController : ControllerBase {
		/// <summary>
		/// </summary>
		/// <param name="manager"></param>
		public TokenApiController(ConfigurationManager manager) => ConfigurationManager = manager;

		/// <summary>
		/// </summary>
		public ConfigurationManager ConfigurationManager { get; }

		/// <summary>
		/// </summary>
		/// <remarks>Get a new token</remarks>
		/// <response code="201">The new token has been created and returned</response>
		/// <response code="500">Unknown error on server</response>
		[HttpGet("/api/token")]
		[ValidateModelState]
		[SwaggerOperation("GetToken")]
		[SwaggerResponse(201, type: typeof(string), description: "The new token has been created and returned")]
		public virtual IActionResult GetToken() {
			var newToken = ConfigurationManager.GetNewToken();
			ConfigurationManager.Add(newToken);
			return StatusCode(201, newToken);
		}

		/// <summary>
		/// </summary>
		/// <remarks>Validate token</remarks>
		/// <param name="token"></param>
		/// <response code="200">Validation completed</response>
		/// <response code="500">Unknown error on server</response>
		[HttpGet("/api/token/validation")]
		[ValidateModelState]
		[SwaggerOperation("ValidateToken")]
		[SwaggerResponse(200, type: typeof(bool?), description: "Validation completed")]
		public virtual IActionResult ValidateToken([FromQuery] [Required] string token) => Ok(ConfigurationManager.Contains(token));
	}
}